[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino
monitor_speed = 115200
lib_deps = 
    project-cycle-arduino-lamp_inferencing
    arduino-libraries/Arduino_LSM9DS1 @ ^1.1.1
    https://github.com/Seeed-Studio/Seeed_RGB_LED_Matrix.git
