/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 09.06.2026 21:20:27

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1472;
#else
constexpr int kTensorArenaSize = 448;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,111 } };
const TfArray<1, float> quant0_scale = { 1, { 0.21959631145000458, } };
const TfArray<1, int> quant0_zero = { 1, { -104 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -38, -32, 60, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00037771195638924837, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  76, 15, 114, -102, -47, 54, 82, -100, -127, 87, 
  67, 70, -32, -74, -113, 12, 42, -96, 16, -22, 
  -103, -23, 118, -1, -108, -95, -107, -58, 111, 33, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0053985011763870716, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -3, -23, 125, 92, 1, 1, -17, -72, -7, 15, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00032993248896673322, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  45, -79, -75, 13, 119, 17, 125, -116, -6, -48, 33, 22, 69, 123, 58, -90, 1, -30, -77, 28, 
  -63, -124, 72, 71, 59, -47, -59, -107, -101, 20, -57, -60, 69, 22, 74, 98, -57, 35, -50, -34, 
  -12, -107, 9, 127, -50, -55, -30, 35, -45, -5, 42, 68, -23, -82, -2, -76, 104, -93, -97, -88, 
  74, 11, 112, 12, -77, 84, -60, -41, -33, 85, 105, 51, -80, -94, 4, -49, -19, -55, 124, 93, 
  -52, 60, -105, -43, -98, 76, -43, 28, -103, 60, 93, 60, -22, 55, 27, -104, -54, 106, 74, 61, 
  -96, 79, -77, 56, -30, -124, -7, 84, -126, -55, 88, 71, -55, 68, -27, -74, -42, 67, -75, 4, 
  100, 55, -66, -90, 93, 85, 13, -38, -27, 7, 72, 47, -78, -48, 9, -19, 62, -18, -16, -40, 
  -24, 94, 46, 63, -19, 91, 89, -126, 121, -39, -70, 118, 72, -34, -113, 54, 87, 1, 9, 89, 
  73, 49, 61, 39, 102, 37, -115, -27, -30, 20, 108, 25, -5, -120, -40, 104, -91, 80, -47, -35, 
  46, -83, -18, 3, 81, 109, -24, 11, 81, -108, -71, 50, -81, -55, 61, -20, -21, 93, -2, 82, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035103871487081051, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 22, 43, 11, 30, 55, -5, -28, 2, -39, 82, 33, 67, 0, -28, 19, 0, 8, -17, 19, -16, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00042641744948923588, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*111] = { 
  -2, -16, -18, 95, 37, 45, 19, -82, 23, -101, -20, 23, -112, -85, -37, 83, 15, 67, -63, -63, 82, -39, 79, 10, -109, 59, -62, -62, -84, -106, 17, 25, 57, -98, -111, 38, -76, 80, 0, -81, 54, -3, -88, -46, -108, 78, -49, 83, -83, -90, -30, -110, 34, -32, -99, 61, 95, 74, 99, 57, 33, -51, 5, -84, -24, -84, -5, 28, 84, -20, 19, -100, -74, -35, -33, -56, 89, 53, -13, 83, 19, -19, -35, 17, -39, -4, -127, -29, -97, -117, 23, -40, -68, 78, -23, -115, 92, 45, -94, -54, -19, -120, 10, 44, -40, -55, -53, -7, -71, -63, 74, 
  -97, -17, 98, 27, -24, 9, 25, 23, 38, 90, -79, 36, 5, 10, 57, -68, 75, 44, 100, -74, -28, -20, 80, -30, 46, 43, -29, 69, -36, -89, -26, 92, 84, 95, 65, -44, -96, 1, 23, -58, -36, -51, 96, 67, 53, -38, 71, -85, -1, -9, -109, -22, -6, -50, -24, -119, -112, 77, 81, -97, -29, 65, -54, -28, -36, -9, 72, -117, 50, -39, 88, -71, 55, -16, 26, 100, -43, -52, 2, 88, -24, -119, -65, -10, 40, -1, -32, -89, 11, -36, 24, 25, 88, 15, -4, 52, -61, -99, 8, -106, 14, 94, -11, -25, -85, 41, 70, -79, -29, -29, -41, 
  67, -1, -94, -73, 53, -62, 59, 86, 101, -13, -89, 10, -86, 47, -69, 72, 32, 61, -1, 43, 104, -105, 56, -88, 10, -30, 101, 51, -59, -88, -58, 68, 52, -82, -24, -39, -96, -6, 71, -91, 60, 61, -98, -21, 35, -23, -58, -92, 32, -33, 51, -28, -23, -4, 55, -92, 9, 11, 9, -32, 97, -40, -20, 16, -33, 60, 20, -64, -35, -39, -8, -109, 5, 91, -31, -89, -77, 60, -54, -72, 34, -69, 30, -12, 1, 8, -37, -9, -92, -8, -84, 84, 18, -46, 101, 67, 28, 48, 32, 25, -111, -100, -62, -84, 43, -49, 90, 71, 3, -25, -58, 
  -82, 55, -58, 70, -5, 67, -9, 105, 52, -94, 87, 85, 49, 63, 41, -30, -89, -59, 30, 62, -77, 38, -75, -48, 60, 50, -84, 59, 85, 64, -54, 39, 85, -54, 60, 7, 101, -99, 15, 74, -84, 71, 3, 83, 100, -91, -12, -75, 59, 43, -77, -10, -28, -117, 19, -90, -100, -113, -50, -20, 92, 31, 96, 71, -79, -104, 55, -100, -76, -106, 56, -64, -65, -85, 34, 44, -25, 116, 46, 112, 28, 74, 77, -32, -19, -86, -10, -44, 63, -47, 40, 32, -94, 10, 85, -46, -70, -27, 80, -30, -40, -14, 83, -68, -57, -11, 8, -34, 15, 26, -95, 
  89, 13, 26, -58, -76, -96, 78, -40, -65, 50, -45, 7, -82, -62, -88, 45, 49, 58, -23, -39, -25, 87, -35, -30, -48, -9, 66, 60, -113, -100, 36, -84, 84, -92, -48, -66, -47, -102, 15, 51, 23, 44, -110, -53, 47, -81, 66, 52, -34, 60, 56, 66, -98, -41, -44, 91, 56, 71, 82, 50, -107, -101, 85, 87, -8, 48, -60, 95, -120, -39, -107, 16, 62, 24, 44, 60, -34, -18, -41, -57, 67, -118, 41, -91, 22, -76, 9, -92, 59, -52, -54, -9, 14, 57, 18, -10, 7, -37, -94, -98, -37, -109, 12, -45, 85, -70, -116, -39, -87, 22, -83, 
  -28, 90, 12, 1, -29, -79, 17, 116, -35, 31, -95, -32, -100, 58, 26, 5, -91, 38, -27, 16, -78, -83, -4, -47, 87, -22, 36, -9, -45, 114, -14, -4, 90, -60, 31, -95, 81, -58, 45, 88, 78, 47, -68, -22, 26, -99, -73, -65, 4, 77, 103, -9, 43, -37, 55, 72, 43, -7, 68, 15, 35, -97, 78, -78, -23, 6, -33, 93, 101, 56, 108, -42, 81, -73, -106, -69, -8, -19, 65, 7, -78, 48, -47, 93, -2, -77, 39, 1, 115, -12, 20, 14, -60, 91, 11, -3, -6, 42, 5, 73, -8, 40, 94, -56, 30, 25, 112, -66, 43, 66, -5, 
  48, -28, -47, -67, -76, -116, -42, 70, -47, 1, -8, -12, -4, 60, 43, -20, -48, -59, 104, 81, -53, 20, -48, 70, -42, -10, 110, -90, 89, 28, 75, -99, 5, -10, -83, 65, -99, 37, -84, 118, -20, 14, -19, -4, -61, -99, 99, -60, -8, -24, -71, 91, -93, 67, 36, -10, 11, 94, 62, -37, -65, 13, 80, -65, 54, 31, -95, 72, -78, -56, 20, 100, -29, 52, 30, 55, 54, 80, 42, -56, 74, 59, -2, 26, -69, -36, 63, 23, -54, -49, -77, 67, -42, 103, -30, -101, -49, -64, -94, -8, -63, -59, 10, -26, 108, -14, -11, -69, -54, 0, -1, 
  89, -111, 29, 92, 92, 46, 43, 57, -23, 103, -12, 117, -27, 53, -62, -96, -27, -50, -66, 109, 98, -63, -51, 4, -19, 110, -24, 35, -98, -11, 29, 106, 27, -91, -34, -96, -13, 37, 63, -27, -19, 31, 123, 118, 49, -3, 31, -84, -56, 61, -67, -23, -15, 22, -30, -64, -90, 78, 76, -104, -70, -31, 58, -75, 61, 34, 29, -42, -47, 112, -63, 22, -18, 47, 16, 27, -53, 64, -52, 69, 124, -93, 78, 9, 41, -89, 59, 60, 83, -27, -17, -82, 24, -53, -82, -40, -29, -85, 13, 108, -27, 71, 2, -90, -7, -31, -42, -88, 109, -32, -55, 
  51, 113, 57, -28, -97, 76, -4, -56, -1, -9, 16, 75, 72, -31, 26, -38, 53, -42, 116, 31, 108, 82, 106, 53, 76, 78, 87, -2, 99, -87, 69, -95, -8, 7, -81, -22, -87, 84, -69, 18, -63, -64, -90, -34, -87, 41, -30, -5, -48, 41, -92, -98, 117, -60, 64, 60, 23, 60, -3, -32, 78, -16, 101, -35, 15, -95, 103, 87, 76, -47, -38, -25, 26, -79, -42, -107, -71, -58, -70, 101, -45, -54, -77, -42, 100, 32, 4, 48, 71, 68, 9, -90, -90, -16, 92, 1, 108, 35, 57, -52, -67, -58, -41, 57, 21, 87, -19, 21, 36, -2, -40, 
  -70, 54, -96, 14, -42, 64, -104, -6, -66, -117, -101, -83, -118, -38, -80, 76, -21, 54, 67, -81, -34, 57, 9, 90, 98, 62, -7, 20, -16, 37, -61, -45, -94, -17, 64, 21, 61, 102, -23, 2, 43, 64, -61, 21, -54, -118, 61, 34, 82, -95, 45, 91, -118, -115, -78, 6, 48, -3, -113, 20, -111, -73, -90, 69, -12, -40, -117, -45, -89, 31, -83, 58, 81, -11, -3, -90, 91, -14, -93, 76, 52, 100, -100, -69, -84, 76, -83, -67, 43, 10, 75, 31, -43, -27, -2, 86, -16, -114, -98, -62, 55, -98, -108, -54, 1, -19, -124, -64, 30, 25, 37, 
  103, 17, 59, -101, -82, -54, 54, 9, -16, 27, -92, 24, 20, -94, 43, -72, -10, -10, 30, 15, -102, 42, -109, 77, 82, -28, -60, -43, 69, 66, -114, -95, -95, -32, 101, 88, -39, -87, -79, 19, 49, -6, -4, -44, -45, 67, -1, -113, 55, 33, -43, -77, -30, -15, 69, 88, -80, -55, 15, -26, 20, 29, 62, 65, 19, -115, -106, 41, 41, 22, 76, 4, -33, -53, -4, 89, 21, -60, 58, 97, -56, -86, 22, -84, -58, 63, -49, 18, -51, -66, -12, 92, 41, -67, -25, -2, -70, 29, -107, 42, 82, 58, 41, 36, 44, -60, -6, -108, 73, -2, -36, 
  3, 43, 89, -16, -65, -83, 120, -34, 85, -20, 100, 106, 75, 101, -43, 45, -50, -43, 91, -5, -32, -32, 96, -6, 23, 33, 59, 43, 99, 31, -19, -34, -7, -56, 18, -36, -88, 44, 15, 60, 63, 93, 105, -10, -54, -37, 22, 47, -96, -10, -87, 65, 25, 28, 90, 53, 44, -31, 2, -98, 72, 48, -14, -40, 66, 54, 60, -39, -34, -37, -95, -8, -73, -78, 106, 40, 37, 103, 63, 34, 64, 112, -80, -48, -92, -87, -61, 59, -9, 74, 56, -85, -108, -84, 14, 28, 44, 68, -23, -34, -19, -13, 77, 71, 61, 35, 4, 101, -7, -99, -29, 
  -50, -104, 1, -35, 66, -94, -65, -106, -88, 52, -25, -101, 27, 58, -38, 80, 14, -37, 91, -30, 51, 61, -69, 68, 55, -35, 8, -53, 91, -29, -47, 26, -106, 98, 67, 68, 88, -72, -92, -68, -13, 17, -88, -53, -109, -43, 101, 62, -16, 109, 72, -97, -109, 20, -72, -107, -74, 33, -21, 48, -36, -79, -84, 72, 17, 27, 72, 41, 9, 75, 0, -52, 50, 70, 30, -108, -43, 83, -94, -94, 17, 47, 92, 70, 101, 83, -100, -63, 4, 66, -78, 98, 22, 18, -75, -99, 39, 11, 70, -25, -75, 64, 52, 35, -3, -91, -8, 87, 55, 17, -6, 
  23, -113, -61, -13, 90, 99, -94, 100, -17, 25, 24, 33, 99, 33, -16, -74, -107, -15, -86, -37, -79, -82, 0, -31, -42, -105, -69, 98, -13, 13, 38, -101, -75, -100, -10, 32, 54, -14, 85, -26, 94, 45, 80, -82, 92, -53, -5, 67, 117, 71, 41, 56, -76, -48, 103, -38, 24, 81, 60, -15, 6, -33, -13, -80, 76, 89, 94, 91, 26, 109, -86, -15, 74, -17, 56, -85, -74, -55, 48, -69, -48, 46, -30, -36, 62, 22, 84, 97, -1, -101, 15, 30, -67, 67, -96, -71, -41, 110, 8, -48, 27, 103, 35, -73, -59, 54, 9, -3, -22, 55, 77, 
  110, -105, -66, 25, 10, -57, -42, 42, 53, 39, 111, -104, -90, 108, -105, -42, -98, 14, 60, -88, 91, 105, -55, 77, -104, -66, -17, -92, 84, -33, 108, -62, -52, 66, -18, -74, -90, 31, 80, -94, -107, 89, -103, 74, -15, 66, -42, -69, -103, -44, -21, 47, 34, -22, -85, -73, 96, -29, 92, -65, 4, 42, -69, 96, 13, 96, 91, 65, -22, 54, 7, -70, 95, -48, 110, 45, -62, 33, 2, 22, 69, 20, -67, -45, 27, -80, 89, 14, -87, 25, -45, 37, -14, 65, -91, 0, 86, 87, 90, 112, -99, 102, -69, 82, -89, -38, 69, -95, -41, -62, -47, 
  0, 92, -81, -103, -102, 30, -13, 18, 40, 36, -7, 42, -61, 51, 51, 85, 18, 48, 38, 65, -100, 92, -89, 48, 25, 1, -49, -40, -21, -60, 29, -38, -39, 57, -8, 23, 0, -101, 28, 97, 63, -52, 32, -78, 77, -67, -98, -27, -80, 75, 45, -9, 77, 93, 44, -62, 95, 48, -79, 91, 3, -68, 20, -47, 17, 45, 17, -65, 10, 70, -94, 89, 88, 94, 45, 78, -46, 25, 92, 41, -77, -64, 15, 103, 109, 84, 10, 57, 62, 109, -3, 108, 22, 69, 104, 77, -90, 54, 58, 50, 83, 95, 104, -33, 74, -69, 17, 43, 108, -63, 33, 
  2, -70, -44, -7, 90, -32, -41, -84, 36, -101, -99, -38, 22, 51, -41, 37, -90, -57, 45, -38, -94, -65, 38, -49, 43, -39, -22, 81, -79, 77, 37, -3, 83, -68, -35, -60, 30, -93, -47, 5, 1, -17, 12, 75, -15, -90, 82, -103, -11, -46, 6, -17, -22, -82, -17, -107, -18, -25, 68, -79, -73, 92, -66, 4, -79, 48, 0, -43, -4, 102, -92, -24, -59, 92, 79, 57, -45, 31, -64, 18, 17, 92, -114, -41, -12, 69, 0, -72, 99, -30, 10, 103, 98, 15, 14, -56, 7, -37, 93, -54, -19, -17, -22, -18, 93, 75, 49, 100, -21, -67, 58, 
  -18, 60, 90, 74, 75, -24, -34, 100, 45, -6, -30, 115, -30, 85, -71, -30, -69, 35, 107, -53, 65, -40, -74, 113, -53, -79, -49, 41, -2, -58, -9, -77, 10, 33, 16, 113, 110, -59, 69, -88, -108, -36, 118, -25, 40, -66, 17, 111, -75, 60, -44, -57, 107, 63, 37, -75, 87, -90, -18, -47, 38, -80, 58, 108, -17, 63, -7, 8, 40, -25, 89, -35, 75, 104, 61, 28, -100, -84, 79, -73, -78, -89, -87, 28, 66, 112, -33, 34, 33, 57, 7, 114, -93, -47, 86, 65, 54, -31, 106, -92, 102, 52, 16, -59, -55, -103, -80, 110, 37, -101, -91, 
  -90, -18, 50, -99, 62, 20, -62, -1, 7, -30, -97, -39, -90, -75, -81, -55, 10, -62, -57, 44, -54, 91, -61, 86, -48, -96, -5, -32, -99, -76, 50, -49, -73, -101, 107, 85, 29, -68, -81, -43, -73, 29, -53, 67, 10, -12, 115, 26, -88, -99, 6, -94, 49, -62, 70, -78, -72, -71, -31, 78, -35, -58, -73, 85, 53, -59, 94, -90, 5, 95, 67, 58, 81, -50, -110, 30, 90, 23, -31, 46, 39, 54, 102, 4, 58, 22, 96, 14, -4, -88, -107, 85, 67, -40, -84, -83, 57, 22, 100, -70, -113, 104, 21, 6, -59, -1, -61, -83, 1, 56, -79, 
  -7, 83, 5, -57, -22, -32, 36, -11, 82, 78, -85, 90, 79, 2, 2, -41, 1, -88, -55, 33, -38, -97, 90, -82, -4, 7, -67, -42, 42, 90, -73, 20, 96, -65, 13, 42, -96, 20, 9, -10, -75, -78, 32, 65, 4, -85, -99, 33, -7, 8, 32, 54, -89, 41, 54, -52, 62, -88, -70, 95, -81, 77, -77, 42, -79, -9, -14, -71, -75, -61, -101, 76, -29, -12, -27, 33, -90, -111, -99, -45, 88, -4, 0, -90, -18, 43, 100, -8, 35, 5, -98, 21, -71, -20, 36, -87, -69, -74, 113, -62, -31, 87, 78, -80, -16, 72, -100, -73, -4, 68, 113, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,111 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0019418243318796158, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.093987494707107544, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.06996607780456543, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.042046342045068741, } };
const TfArray<1, int> quant9_zero = { 1, { 44 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 111, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2220, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 112), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1025223_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1025223_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1025223_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1025223_4_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1025223_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
